name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v0.5
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: raco pkg install --name rival --no-cache --auto
      - name: "Install nightly dependency on biginterval"
        run: raco pkg install --name biginterval --no-cache --auto
      - run: raco test *.rkt
