name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: stable
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: raco pkg install --name rival --no-cache --auto
      - name: "Install raco fmt"
        run: raco pkg install --auto fmt
      - name: "Run tests"
        run: raco test .
      - name: "Reformat all of the source code"
        run: raco fmt -i **/*.rkt
      - name: "Make sure files are correctly formatted with raco fmt"
        run: git diff --exit-code
